PSP-3889:Field label suggestions for Property Information tab
bcgov/PSP pull request #2113
Opened 2022-09-19 20:56 UTC by Maheshbabu28

2022-09-20 15:58 UTC, devinleighsmith reviewed
I have a question out to Dev on this one, will approve when I receive a response.

2022-09-20 16:21 UTC, Maheshbabu28 commented
![image](https://user-images.githubusercontent.com/102620827/191311595-3d843b65-2845-4e15-ba37-5cb79b49002b.png)

![image](https://user-images.githubusercontent.com/102620827/191311725-28f7c675-2d42-4604-b263-59426ffff476.png)

2022-09-20 22:35 UTC, devinleighsmith requested changes
see correction from Dev

2022-09-20 23:03 UTC, Maheshbabu28 commented on frontend/src/features/mapSideBar/tabs/propertyDetails/detail/PropertyDetailsTabView.tsx
> +            <SectionField label="Adjacent Land Type">
![image](https://user-images.githubusercontent.com/102620827/191379783-79b86d77-dbc3-4e9a-84bc-d38370bdd257.png)

2022-09-23 03:41 UTC, devinleighsmith approved these changes

2022-09-23 15:23 UTC, merged