Fixes to the Lease view screen
bcgov/PSP pull request #2943
Opened 2023-02-28 23:44 UTC by FuriousLlama

2023-03-01 20:21 UTC, devinleighsmith commented on source/frontend/src/features/leases/detail/LeasePages/details/DetailAdministration.tsx
> +          {prettyFormatDate(responsabilityDate)}
nit: responsibilityDate

2023-03-01 20:29 UTC, devinleighsmith commented
Not seeing this requirement satisfied: PID should have it's own space to be displayed, not following Legal description content

2023-03-01 20:30 UTC, devinleighsmith commented
@FuriousLlama this doesn't seem fixed either unless I'm missing something: **Initiator data is not displayed even an option has been selected.**

2023-03-01 20:30 UTC, devinleighsmith commented
Did this get fixed? **Responibility field displays "Headquarter" on the View Form if the user doesn't select any option in particular (Option left with default value "Select group responsible")**

2023-03-01 20:31 UTC, devinleighsmith commented
@FuriousLlama this still seems to be a problem as well: **In case an address is not present, the "Address not available in PIMS" should be located next to the Address label**

2023-03-01 20:31 UTC, devinleighsmith requested changes
see comments, not all AC items addressed yet.

2023-03-02 00:41 UTC, devinleighsmith approved these changes
Based on discussion giving approval so that if you want to merge once you fix the actual bugs you can.

2023-03-02 01:00 UTC, FuriousLlama commented on source/frontend/src/features/leases/detail/LeasePages/details/LeaseDetailsForm.tsx
> +        <DetailDocumentation disabled={true} />
This needs to be refactored given the underlying components are only used for view

2023-03-02 17:23 UTC, merged