PSP-6739 : FT:Reg: User with limited access to region is not filterin…
bcgov/PSP pull request #3412
Opened 2023-08-14 23:48 UTC by eddherrera

…g as expected in the L/L view screen

2023-08-15 00:04 UTC, devinleighsmith approved these changes

2023-08-15 01:09 UTC, devinleighsmith commented
@eddherrera there is a test failure here.

2023-08-15 01:10 UTC, devinleighsmith requested changes
lets hold off on merging this, the fact that we had a unit test for this makes me nervous.

2023-08-17 17:55 UTC, eddherrera commented
> lets hold off on merging this, the fact that we had a unit test for this makes me nervous.

@devinleighsmith I think we can close this PR.

2023-08-17 19:57 UTC, closed without merging