PSP-8474 | Fixed property updates removing is-owned
bcgov/PSP pull request #4037
Opened 2024-05-22 23:02 UTC by FuriousLlama

2024-05-22 23:28 UTC, devinleighsmith requested changes
Please increment the hotfix version @FuriousLlama to v5.2.3-79.18

2024-05-22 23:29 UTC, devinleighsmith commented
@FuriousLlama would it make sense to update the property repository to prevent this field from being set at all by the property service? I think only the take service should be allowed to change ownership, correct?

2024-05-23 00:52 UTC, FuriousLlama commented
> @FuriousLlama would it make sense to update the property repository to prevent this field from being set at all by the property service? I think only the take service should be allowed to change ownership, correct?

That could work. We could design something more robust that inclues other fields as well like location and prevents updates to those. For now, I think this change is sufficient

2024-05-23 04:36 UTC, devinleighsmith approved these changes

2024-05-23 04:36 UTC, merged