Release 5.4
bcgov/PSP pull request #4264
Opened 2024-08-14 00:24 UTC by devinleighsmith

2024-08-14 17:47 UTC, eddherrera approved these changes

2024-08-15 16:33 UTC, FuriousLlama requested changes
Blocking the pr until release has been completed

2024-08-18 23:27 UTC, devinleighsmith commented
@FuriousLlama the release of code is the first (required) step in order for the release to be completed!

2024-08-18 23:52 UTC, FuriousLlama approved these changes
Looks good for release

2024-08-19 14:39 UTC, merged