PSP-8802 | Updated frontend with matching propery attributes. Removed IProperty
bcgov/PSP pull request #4268
Opened 2024-08-16 23:18 UTC by FuriousLlama

2024-08-18 23:10 UTC, devinleighsmith requested changes
On testing this, I had request failures to the LOCATION_VW and BOUNDARY_VW on my local due to:
<ows:ExceptionReport
 
xmlns:xs
="
http://www.w3.org/2001/XMLSchema
"
 
xmlns:ows
="
http://www.opengis.net/ows/1.1
"
 
xmlns:xsi
="
http://www.w3.org/2001/XMLSchema-instance
"
 
version
="
2.0.0
"
 
xsi:schemaLocation
="
http://www.opengis.net/ows/1.1 http://localhost:8600/geoserver/schemas/ows/1.1.0/owsAll.xsd
"
>
<ows:Exception
 
exceptionCode
="
NoApplicableCode
"
>
<ows:ExceptionText
>
java.lang.RuntimeException: java.io.IOException
java.io.IOExceptioncom.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name &apos;PROPERTY_CLASSIFICATION_TYPE_CODE&apos;.
Invalid column name &apos;PROPERTY_CLASSIFICATION_TYPE_CODE&apos;.
</ows:ExceptionText
>
</ows:Exception>
</ows:ExceptionReport>

this would seem to imply that the layers need to be regenerated to take into account the new schema. That should update the geoserver xml (which we commit).

2024-08-18 23:10 UTC, devinleighsmith commented
Also, please make sure this story is flagged with manual_changes_required so we remember to update geoserver when we deploy this.

2024-08-19 16:28 UTC, FuriousLlama commented
> On testing this, I had request failures to the LOCATION_VW and BOUNDARY_VW on my local due to: <ows:ExceptionReport
> 
> xmlns:xs =" http://www.w3.org/2001/XMLSchema "
> 
> xmlns:ows =" http://www.opengis.net/ows/1.1 "
> 
> xmlns:xsi =" http://www.w3.org/2001/XMLSchema-instance "
> 
> version =" 2.0.0 "
> 
> xsi:schemaLocation =" http://www.opengis.net/ows/1.1 http://localhost:8600/geoserver/schemas/ows/1.1.0/owsAll.xsd "
> 
> > 
> 
> <ows:Exception
> 
> exceptionCode =" NoApplicableCode "
> 
> > 
> 
> <ows:ExceptionText
> 
> > 
> 
> java.lang.RuntimeException: java.io.IOException java.io.IOExceptioncom.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'PROPERTY_CLASSIFICATION_TYPE_CODE'. Invalid column name 'PROPERTY_CLASSIFICATION_TYPE_CODE'. </ows:ExceptionText
> 
> > 
> 
> </ows:Exception> </ows:ExceptionReport>
> 
> this would seem to imply that the layers need to be regenerated to take into account the new schema. That should update the geoserver xml (which we commit).

The XML that you are referring to has no information about the attributes themselves. Instead, it uses an identifier for the internal datastore. That needs to be updated manually given the identifier is generated by geoserver. I've added the label to the story to make sure it gets done during deployment.

2024-08-20 00:10 UTC, devinleighsmith approved these changes

2024-08-20 00:10 UTC, merged